#############################################################################
# Makefile for building: NTUADAQ
# Generated by qmake (2.01a) (Qt 4.7.2) on: Wed Sep 28 21:28:00 2011
# Project:  NTUADAQ.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile NTUADAQ.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Isrc -I$(ROOTSYS)/include -I/usr/include -I../root/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -L/home/nick/root/lib -pthread -lm -ldl -rdynamic -L/usr/lib/ -lCAENVME -L/home/nick/root/lib/ -lGpad -lCint -lCore -lGraf -lGraf3d -lHist -lGui -lTree -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lRIO -lNet -lThread -lGQt -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/ConfigFile.cpp \
		src/Interface.cpp \
		src/main.cpp \
		src/V462_GateGenerator.cpp \
		src/V550_CRAMS.cpp \
		src/V551_Sequencer.cpp moc_Interface.cpp
OBJECTS       = ConfigFile.o \
		Interface.o \
		main.o \
		V462_GateGenerator.o \
		V550_CRAMS.o \
		V551_Sequencer.o \
		moc_Interface.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		../root/include/rootlibs.pri \
		../root/include/rootcintrule.pri \
		../root/include/rootcint.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		NTUADAQ.pro
QMAKE_TARGET  = NTUADAQ
DESTDIR       = 
TARGET        = NTUADAQ

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_interface.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: NTUADAQ.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		../root/include/rootlibs.pri \
		../root/include/rootcintrule.pri \
		../root/include/rootcint.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtCore.prl \
		/usr/lib/libQtGui.prl
	$(QMAKE) -o Makefile NTUADAQ.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
../root/include/rootlibs.pri:
../root/include/rootcintrule.pri:
../root/include/rootcint.pri:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtCore.prl:
/usr/lib/libQtGui.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile NTUADAQ.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/NTUADAQ1.0.0 || $(MKDIR) .tmp/NTUADAQ1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/NTUADAQ1.0.0/ && $(COPY_FILE) --parents src/ConfigFile.h src/Interface.h src/V462_GateGenerator.h src/V550_CRAMS.h src/V551_Sequencer.h .tmp/NTUADAQ1.0.0/ && $(COPY_FILE) --parents src/ConfigFile.cpp src/Interface.cpp src/main.cpp src/V462_GateGenerator.cpp src/V550_CRAMS.cpp src/V551_Sequencer.cpp .tmp/NTUADAQ1.0.0/ && $(COPY_FILE) --parents src/interface.ui .tmp/NTUADAQ1.0.0/ && (cd `dirname .tmp/NTUADAQ1.0.0` && $(TAR) NTUADAQ1.0.0.tar NTUADAQ1.0.0 && $(COMPRESS) NTUADAQ1.0.0.tar) && $(MOVE) `dirname .tmp/NTUADAQ1.0.0`/NTUADAQ1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/NTUADAQ1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_Interface.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Interface.cpp
moc_Interface.cpp: /usr/include/stdint.h \
		/usr/include/features.h \
		/usr/include/bits/predefs.h \
		/usr/include/sys/cdefs.h \
		/usr/include/bits/wordsize.h \
		/usr/include/gnu/stubs.h \
		/usr/include/gnu/stubs-32.h \
		/usr/include/bits/wchar.h \
		/usr/include/arpa/inet.h \
		/usr/include/netinet/in.h \
		/usr/include/sys/socket.h \
		/usr/include/sys/uio.h \
		/usr/include/sys/types.h \
		/usr/include/bits/types.h \
		/usr/include/bits/typesizes.h \
		/usr/include/time.h \
		/usr/include/bits/time.h \
		/usr/include/xlocale.h \
		/usr/include/endian.h \
		/usr/include/bits/endian.h \
		/usr/include/bits/byteswap.h \
		/usr/include/sys/select.h \
		/usr/include/bits/select.h \
		/usr/include/bits/sigset.h \
		/usr/include/sys/sysmacros.h \
		/usr/include/bits/pthreadtypes.h \
		/usr/include/bits/uio.h \
		/usr/include/bits/socket.h \
		/usr/include/bits/sockaddr.h \
		/usr/include/bits/socket2.h \
		/usr/include/bits/in.h \
		/usr/include/stdlib.h \
		/usr/include/bits/waitflags.h \
		/usr/include/bits/waitstatus.h \
		/usr/include/alloca.h \
		/usr/include/bits/stdlib.h \
		/usr/include/bits/stdlib-ldbl.h \
		src/V551_Sequencer.h \
		/usr/include/CAENVMElib.h \
		/usr/include/stdio.h \
		/usr/include/libio.h \
		/usr/include/_G_config.h \
		/usr/include/wchar.h \
		/usr/include/wctype.h \
		/usr/include/bits/wchar2.h \
		/usr/include/bits/wchar-ldbl.h \
		/usr/include/gconv.h \
		/usr/include/bits/stdio-lock.h \
		/usr/include/bits/libc-lock.h \
		/usr/include/pthread.h \
		/usr/include/sched.h \
		/usr/include/bits/sched.h \
		/usr/include/bits/setjmp.h \
		/usr/include/errno.h \
		/usr/include/bits/errno.h \
		/usr/include/linux/errno.h \
		/usr/include/gnu/option-groups.h \
		/usr/include/bits/libio-ldbl.h \
		/usr/include/bits/stdio_lim.h \
		/usr/include/bits/sys_errlist.h \
		/usr/include/getopt.h \
		/usr/include/ctype.h \
		/usr/include/bits/stdio.h \
		/usr/include/bits/stdio2.h \
		/usr/include/bits/stdio-ldbl.h \
		/usr/include/malloc.h \
		/usr/include/CAENVMEoslib.h \
		/usr/include/CAENVMEtypes.h \
		src/V550_CRAMS.h \
		src/V462_GateGenerator.h \
		src/ConfigFile.h \
		/usr/include/sys/stat.h \
		/usr/include/bits/stat.h \
		/usr/include/unistd.h \
		/usr/include/bits/posix_opt.h \
		/usr/include/bits/environments.h \
		/usr/include/bits/confname.h \
		/usr/include/bits/unistd.h \
		$(ROOTSYS)/include/TEnv.h \
		../root/include/TObject.h \
		../root/include/Rtypes.h \
		../root/include/RConfig.h \
		../root/include/RVersion.h \
		../root/include/DllImport.h \
		../root/include/Rtypeinfo.h \
		/usr/include/string.h \
		/usr/include/bits/string.h \
		/usr/include/bits/string2.h \
		/usr/include/bits/string3.h \
		$(ROOTSYS)/include/snprintf.h \
		$(ROOTSYS)/include/strlcpy.h \
		../root/include/TGenericClassInfo.h \
		../root/include/TSchemaHelper.h \
		../root/include/TStorage.h \
		../root/include/TVersionCheck.h \
		../root/include/Riosfwd.h \
		../root/include/TBuffer.h \
		../root/include/TString.h \
		../root/include/TMathBase.h \
		$(ROOTSYS)/include/TROOT.h \
		../root/include/TDirectory.h \
		../root/include/TNamed.h \
		../root/include/TList.h \
		../root/include/TSeqCollection.h \
		../root/include/TCollection.h \
		../root/include/TIterator.h \
		../root/include/TDatime.h \
		../root/include/TUUID.h \
		$(ROOTSYS)/include/TRint.h \
		../root/include/TApplication.h \
		$(ROOTSYS)/include/TQObject.h \
		../root/include/TQClass.h \
		../root/include/TClass.h \
		../root/include/TDictionary.h \
		../root/include/Property.h \
		$(ROOTSYS)/include/TObjArray.h \
		../root/include/TObjString.h \
		../root/include/TApplicationImp.h \
		$(ROOTSYS)/include/TSystem.h \
		/usr/include/fcntl.h \
		/usr/include/bits/fcntl.h \
		/usr/include/bits/fcntl2.h \
		../root/include/TInetAddress.h \
		$(ROOTSYS)/include/TTimer.h \
		../root/include/TSysEvtHandler.h \
		../root/include/TTime.h \
		$(ROOTSYS)/include/TQtWidget.h \
		/usr/include/assert.h \
		$(ROOTSYS)/include/TCanvas.h \
		../root/include/TPad.h \
		../root/include/TVirtualPad.h \
		../root/include/TAttPad.h \
		../root/include/TVirtualX.h \
		../root/include/TAttLine.h \
		../root/include/TAttFill.h \
		../root/include/TAttText.h \
		../root/include/TAttMarker.h \
		../root/include/GuiTypes.h \
		../root/include/Buttons.h \
		../root/include/TAttCanvas.h \
		../root/include/TCanvasImp.h \
		../root/include/TQtCanvasPainter.h \
		$(ROOTSYS)/include/TF1.h \
		$(ROOTSYS)/include/TFormula.h \
		../root/include/TBits.h \
		../root/include/Math/ParamFunctor.h \
		$(ROOTSYS)/include/TGQt.h \
		../root/include/TQtRConfig.h \
		../root/include/TQtClientGuard.h \
		../root/include/TQtClientWidget.h \
		../root/include/TQtEmitter.h \
		../root/include/TVirtualX.interface.h \
		$(ROOTSYS)/include/TH1F.h \
		$(ROOTSYS)/include/TH1.h \
		../root/include/TAxis.h \
		../root/include/TAttAxis.h \
		../root/include/TArrayD.h \
		../root/include/TArray.h \
		../root/include/TArrayC.h \
		../root/include/TArrayS.h \
		../root/include/TArrayI.h \
		../root/include/TArrayF.h \
		../root/include/Foption.h \
		../root/include/TVectorFfwd.h \
		../root/include/TVectorDfwd.h \
		../root/include/TFitResultPtr.h \
		$(ROOTSYS)/include/TFrame.h \
		../root/include/TWbox.h \
		../root/include/TBox.h \
		../root/include/TColor.h \
		$(ROOTSYS)/include/TGedFrame.h \
		../root/include/TGFrame.h \
		../root/include/TGWindow.h \
		../root/include/TGObject.h \
		../root/include/TGClient.h \
		../root/include/TGDimension.h \
		../root/include/TGGC.h \
		../root/include/TRefCnt.h \
		../root/include/TGFont.h \
		../root/include/TGLayout.h \
		../root/include/TGString.h \
		$(ROOTSYS)/include/TGedEditor.h \
		../root/include/TVirtualPadEditor.h \
		../root/include/TMap.h \
		../root/include/THashTable.h \
		src/Interface.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/Interface.h -o moc_Interface.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_interface.h
compiler_uic_clean:
	-$(DEL_FILE) ui_interface.h
ui_interface.h: src/interface.ui
	/usr/bin/uic-qt4 src/interface.ui -o ui_interface.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

ConfigFile.o: src/ConfigFile.cpp src/ConfigFile.h \
		/usr/include/sys/stat.h \
		/usr/include/features.h \
		/usr/include/bits/predefs.h \
		/usr/include/sys/cdefs.h \
		/usr/include/bits/wordsize.h \
		/usr/include/gnu/stubs.h \
		/usr/include/gnu/stubs-32.h \
		/usr/include/bits/types.h \
		/usr/include/bits/typesizes.h \
		/usr/include/time.h \
		/usr/include/bits/time.h \
		/usr/include/xlocale.h \
		/usr/include/bits/stat.h \
		/usr/include/unistd.h \
		/usr/include/bits/posix_opt.h \
		/usr/include/bits/environments.h \
		/usr/include/bits/confname.h \
		/usr/include/getopt.h \
		/usr/include/ctype.h \
		/usr/include/endian.h \
		/usr/include/bits/endian.h \
		/usr/include/bits/byteswap.h \
		/usr/include/bits/unistd.h \
		/usr/include/stdint.h \
		/usr/include/bits/wchar.h \
		$(ROOTSYS)/include/TEnv.h \
		../root/include/TObject.h \
		../root/include/Rtypes.h \
		../root/include/RConfig.h \
		../root/include/RVersion.h \
		/usr/include/stdlib.h \
		/usr/include/bits/waitflags.h \
		/usr/include/bits/waitstatus.h \
		/usr/include/sys/types.h \
		/usr/include/sys/select.h \
		/usr/include/bits/select.h \
		/usr/include/bits/sigset.h \
		/usr/include/sys/sysmacros.h \
		/usr/include/bits/pthreadtypes.h \
		/usr/include/alloca.h \
		/usr/include/bits/stdlib.h \
		/usr/include/bits/stdlib-ldbl.h \
		../root/include/DllImport.h \
		../root/include/Rtypeinfo.h \
		/usr/include/stdio.h \
		/usr/include/libio.h \
		/usr/include/_G_config.h \
		/usr/include/wchar.h \
		/usr/include/wctype.h \
		/usr/include/bits/wchar2.h \
		/usr/include/bits/wchar-ldbl.h \
		/usr/include/gconv.h \
		/usr/include/bits/stdio-lock.h \
		/usr/include/bits/libc-lock.h \
		/usr/include/pthread.h \
		/usr/include/sched.h \
		/usr/include/bits/sched.h \
		/usr/include/bits/setjmp.h \
		/usr/include/errno.h \
		/usr/include/bits/errno.h \
		/usr/include/linux/errno.h \
		/usr/include/gnu/option-groups.h \
		/usr/include/bits/libio-ldbl.h \
		/usr/include/bits/stdio_lim.h \
		/usr/include/bits/sys_errlist.h \
		/usr/include/bits/stdio.h \
		/usr/include/bits/stdio2.h \
		/usr/include/bits/stdio-ldbl.h \
		/usr/include/string.h \
		/usr/include/bits/string.h \
		/usr/include/bits/string2.h \
		/usr/include/bits/string3.h \
		$(ROOTSYS)/include/snprintf.h \
		$(ROOTSYS)/include/strlcpy.h \
		../root/include/TGenericClassInfo.h \
		../root/include/TSchemaHelper.h \
		../root/include/TStorage.h \
		../root/include/TVersionCheck.h \
		../root/include/Riosfwd.h \
		../root/include/TBuffer.h \
		../root/include/TString.h \
		../root/include/TMathBase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ConfigFile.o src/ConfigFile.cpp

Interface.o: src/Interface.cpp src/ConfigFile.h \
		/usr/include/sys/stat.h \
		/usr/include/features.h \
		/usr/include/bits/predefs.h \
		/usr/include/sys/cdefs.h \
		/usr/include/bits/wordsize.h \
		/usr/include/gnu/stubs.h \
		/usr/include/gnu/stubs-32.h \
		/usr/include/bits/types.h \
		/usr/include/bits/typesizes.h \
		/usr/include/time.h \
		/usr/include/bits/time.h \
		/usr/include/xlocale.h \
		/usr/include/bits/stat.h \
		/usr/include/unistd.h \
		/usr/include/bits/posix_opt.h \
		/usr/include/bits/environments.h \
		/usr/include/bits/confname.h \
		/usr/include/getopt.h \
		/usr/include/ctype.h \
		/usr/include/endian.h \
		/usr/include/bits/endian.h \
		/usr/include/bits/byteswap.h \
		/usr/include/bits/unistd.h \
		/usr/include/stdint.h \
		/usr/include/bits/wchar.h \
		$(ROOTSYS)/include/TEnv.h \
		../root/include/TObject.h \
		../root/include/Rtypes.h \
		../root/include/RConfig.h \
		../root/include/RVersion.h \
		/usr/include/stdlib.h \
		/usr/include/bits/waitflags.h \
		/usr/include/bits/waitstatus.h \
		/usr/include/sys/types.h \
		/usr/include/sys/select.h \
		/usr/include/bits/select.h \
		/usr/include/bits/sigset.h \
		/usr/include/sys/sysmacros.h \
		/usr/include/bits/pthreadtypes.h \
		/usr/include/alloca.h \
		/usr/include/bits/stdlib.h \
		/usr/include/bits/stdlib-ldbl.h \
		../root/include/DllImport.h \
		../root/include/Rtypeinfo.h \
		/usr/include/stdio.h \
		/usr/include/libio.h \
		/usr/include/_G_config.h \
		/usr/include/wchar.h \
		/usr/include/wctype.h \
		/usr/include/bits/wchar2.h \
		/usr/include/bits/wchar-ldbl.h \
		/usr/include/gconv.h \
		/usr/include/bits/stdio-lock.h \
		/usr/include/bits/libc-lock.h \
		/usr/include/pthread.h \
		/usr/include/sched.h \
		/usr/include/bits/sched.h \
		/usr/include/bits/setjmp.h \
		/usr/include/errno.h \
		/usr/include/bits/errno.h \
		/usr/include/linux/errno.h \
		/usr/include/gnu/option-groups.h \
		/usr/include/bits/libio-ldbl.h \
		/usr/include/bits/stdio_lim.h \
		/usr/include/bits/sys_errlist.h \
		/usr/include/bits/stdio.h \
		/usr/include/bits/stdio2.h \
		/usr/include/bits/stdio-ldbl.h \
		/usr/include/string.h \
		/usr/include/bits/string.h \
		/usr/include/bits/string2.h \
		/usr/include/bits/string3.h \
		$(ROOTSYS)/include/snprintf.h \
		$(ROOTSYS)/include/strlcpy.h \
		../root/include/TGenericClassInfo.h \
		../root/include/TSchemaHelper.h \
		../root/include/TStorage.h \
		../root/include/TVersionCheck.h \
		../root/include/Riosfwd.h \
		../root/include/TBuffer.h \
		../root/include/TString.h \
		../root/include/TMathBase.h \
		src/Interface.h \
		/usr/include/arpa/inet.h \
		/usr/include/netinet/in.h \
		/usr/include/sys/socket.h \
		/usr/include/sys/uio.h \
		/usr/include/bits/uio.h \
		/usr/include/bits/socket.h \
		/usr/include/bits/sockaddr.h \
		/usr/include/bits/socket2.h \
		/usr/include/bits/in.h \
		src/V551_Sequencer.h \
		/usr/include/CAENVMElib.h \
		/usr/include/malloc.h \
		/usr/include/CAENVMEoslib.h \
		/usr/include/CAENVMEtypes.h \
		src/V550_CRAMS.h \
		src/V462_GateGenerator.h \
		$(ROOTSYS)/include/TROOT.h \
		../root/include/TDirectory.h \
		../root/include/TNamed.h \
		../root/include/TList.h \
		../root/include/TSeqCollection.h \
		../root/include/TCollection.h \
		../root/include/TIterator.h \
		../root/include/TDatime.h \
		../root/include/TUUID.h \
		$(ROOTSYS)/include/TRint.h \
		../root/include/TApplication.h \
		$(ROOTSYS)/include/TQObject.h \
		../root/include/TQClass.h \
		../root/include/TClass.h \
		../root/include/TDictionary.h \
		../root/include/Property.h \
		$(ROOTSYS)/include/TObjArray.h \
		../root/include/TObjString.h \
		../root/include/TApplicationImp.h \
		$(ROOTSYS)/include/TSystem.h \
		/usr/include/fcntl.h \
		/usr/include/bits/fcntl.h \
		/usr/include/bits/fcntl2.h \
		../root/include/TInetAddress.h \
		$(ROOTSYS)/include/TTimer.h \
		../root/include/TSysEvtHandler.h \
		../root/include/TTime.h \
		$(ROOTSYS)/include/TQtWidget.h \
		/usr/include/assert.h \
		$(ROOTSYS)/include/TCanvas.h \
		../root/include/TPad.h \
		../root/include/TVirtualPad.h \
		../root/include/TAttPad.h \
		../root/include/TVirtualX.h \
		../root/include/TAttLine.h \
		../root/include/TAttFill.h \
		../root/include/TAttText.h \
		../root/include/TAttMarker.h \
		../root/include/GuiTypes.h \
		../root/include/Buttons.h \
		../root/include/TAttCanvas.h \
		../root/include/TCanvasImp.h \
		../root/include/TQtCanvasPainter.h \
		$(ROOTSYS)/include/TF1.h \
		$(ROOTSYS)/include/TFormula.h \
		../root/include/TBits.h \
		../root/include/Math/ParamFunctor.h \
		$(ROOTSYS)/include/TGQt.h \
		../root/include/TQtRConfig.h \
		../root/include/TQtClientGuard.h \
		../root/include/TQtClientWidget.h \
		../root/include/TQtEmitter.h \
		../root/include/TVirtualX.interface.h \
		$(ROOTSYS)/include/TH1F.h \
		$(ROOTSYS)/include/TH1.h \
		../root/include/TAxis.h \
		../root/include/TAttAxis.h \
		../root/include/TArrayD.h \
		../root/include/TArray.h \
		../root/include/TArrayC.h \
		../root/include/TArrayS.h \
		../root/include/TArrayI.h \
		../root/include/TArrayF.h \
		../root/include/Foption.h \
		../root/include/TVectorFfwd.h \
		../root/include/TVectorDfwd.h \
		../root/include/TFitResultPtr.h \
		$(ROOTSYS)/include/TFrame.h \
		../root/include/TWbox.h \
		../root/include/TBox.h \
		../root/include/TColor.h \
		$(ROOTSYS)/include/TGedFrame.h \
		../root/include/TGFrame.h \
		../root/include/TGWindow.h \
		../root/include/TGObject.h \
		../root/include/TGClient.h \
		../root/include/TGDimension.h \
		../root/include/TGGC.h \
		../root/include/TRefCnt.h \
		../root/include/TGFont.h \
		../root/include/TGLayout.h \
		../root/include/TGString.h \
		$(ROOTSYS)/include/TGedEditor.h \
		../root/include/TVirtualPadEditor.h \
		../root/include/TMap.h \
		../root/include/THashTable.h \
		ui_interface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Interface.o src/Interface.cpp

main.o: src/main.cpp /usr/include/stdlib.h \
		/usr/include/features.h \
		/usr/include/bits/predefs.h \
		/usr/include/sys/cdefs.h \
		/usr/include/bits/wordsize.h \
		/usr/include/gnu/stubs.h \
		/usr/include/gnu/stubs-32.h \
		/usr/include/bits/waitflags.h \
		/usr/include/bits/waitstatus.h \
		/usr/include/endian.h \
		/usr/include/bits/endian.h \
		/usr/include/bits/byteswap.h \
		/usr/include/xlocale.h \
		/usr/include/sys/types.h \
		/usr/include/bits/types.h \
		/usr/include/bits/typesizes.h \
		/usr/include/time.h \
		/usr/include/bits/time.h \
		/usr/include/sys/select.h \
		/usr/include/bits/select.h \
		/usr/include/bits/sigset.h \
		/usr/include/sys/sysmacros.h \
		/usr/include/bits/pthreadtypes.h \
		/usr/include/alloca.h \
		/usr/include/bits/stdlib.h \
		/usr/include/bits/stdlib-ldbl.h \
		../root/include/TApplication.h \
		../root/include/TObject.h \
		../root/include/Rtypes.h \
		../root/include/RConfig.h \
		../root/include/RVersion.h \
		../root/include/DllImport.h \
		../root/include/Rtypeinfo.h \
		/usr/include/stdio.h \
		/usr/include/libio.h \
		/usr/include/_G_config.h \
		/usr/include/wchar.h \
		/usr/include/bits/wchar.h \
		/usr/include/wctype.h \
		/usr/include/bits/wchar2.h \
		/usr/include/bits/wchar-ldbl.h \
		/usr/include/gconv.h \
		/usr/include/bits/stdio-lock.h \
		/usr/include/bits/libc-lock.h \
		/usr/include/pthread.h \
		/usr/include/sched.h \
		/usr/include/bits/sched.h \
		/usr/include/bits/setjmp.h \
		/usr/include/errno.h \
		/usr/include/bits/errno.h \
		/usr/include/linux/errno.h \
		/usr/include/gnu/option-groups.h \
		/usr/include/bits/libio-ldbl.h \
		/usr/include/bits/stdio_lim.h \
		/usr/include/bits/sys_errlist.h \
		/usr/include/getopt.h \
		/usr/include/ctype.h \
		/usr/include/bits/stdio.h \
		/usr/include/bits/stdio2.h \
		/usr/include/bits/stdio-ldbl.h \
		/usr/include/string.h \
		/usr/include/bits/string.h \
		/usr/include/bits/string2.h \
		/usr/include/bits/string3.h \
		$(ROOTSYS)/include/snprintf.h \
		$(ROOTSYS)/include/strlcpy.h \
		/usr/include/unistd.h \
		/usr/include/bits/posix_opt.h \
		/usr/include/bits/environments.h \
		/usr/include/bits/confname.h \
		/usr/include/bits/unistd.h \
		../root/include/TGenericClassInfo.h \
		../root/include/TSchemaHelper.h \
		../root/include/TStorage.h \
		../root/include/TVersionCheck.h \
		../root/include/Riosfwd.h \
		../root/include/TBuffer.h \
		$(ROOTSYS)/include/TQObject.h \
		../root/include/TString.h \
		../root/include/TMathBase.h \
		../root/include/TQClass.h \
		../root/include/TClass.h \
		../root/include/TDictionary.h \
		../root/include/TNamed.h \
		../root/include/Property.h \
		$(ROOTSYS)/include/TObjArray.h \
		../root/include/TSeqCollection.h \
		../root/include/TCollection.h \
		../root/include/TIterator.h \
		../root/include/TObjString.h \
		../root/include/TApplicationImp.h \
		$(ROOTSYS)/include/TSystem.h \
		/usr/include/fcntl.h \
		/usr/include/bits/fcntl.h \
		/usr/include/bits/uio.h \
		/usr/include/bits/stat.h \
		/usr/include/bits/fcntl2.h \
		../root/include/TInetAddress.h \
		$(ROOTSYS)/include/TTimer.h \
		../root/include/TSysEvtHandler.h \
		../root/include/TTime.h \
		src/Interface.h \
		/usr/include/stdint.h \
		/usr/include/arpa/inet.h \
		/usr/include/netinet/in.h \
		/usr/include/sys/socket.h \
		/usr/include/sys/uio.h \
		/usr/include/bits/socket.h \
		/usr/include/bits/sockaddr.h \
		/usr/include/bits/socket2.h \
		/usr/include/bits/in.h \
		src/V551_Sequencer.h \
		/usr/include/CAENVMElib.h \
		/usr/include/malloc.h \
		/usr/include/CAENVMEoslib.h \
		/usr/include/CAENVMEtypes.h \
		src/V550_CRAMS.h \
		src/V462_GateGenerator.h \
		src/ConfigFile.h \
		/usr/include/sys/stat.h \
		$(ROOTSYS)/include/TEnv.h \
		$(ROOTSYS)/include/TROOT.h \
		../root/include/TDirectory.h \
		../root/include/TList.h \
		../root/include/TDatime.h \
		../root/include/TUUID.h \
		$(ROOTSYS)/include/TRint.h \
		$(ROOTSYS)/include/TQtWidget.h \
		/usr/include/assert.h \
		$(ROOTSYS)/include/TCanvas.h \
		../root/include/TPad.h \
		../root/include/TVirtualPad.h \
		../root/include/TAttPad.h \
		../root/include/TVirtualX.h \
		../root/include/TAttLine.h \
		../root/include/TAttFill.h \
		../root/include/TAttText.h \
		../root/include/TAttMarker.h \
		../root/include/GuiTypes.h \
		../root/include/Buttons.h \
		../root/include/TAttCanvas.h \
		../root/include/TCanvasImp.h \
		../root/include/TQtCanvasPainter.h \
		$(ROOTSYS)/include/TF1.h \
		$(ROOTSYS)/include/TFormula.h \
		../root/include/TBits.h \
		../root/include/Math/ParamFunctor.h \
		$(ROOTSYS)/include/TGQt.h \
		../root/include/TQtRConfig.h \
		../root/include/TQtClientGuard.h \
		../root/include/TQtClientWidget.h \
		../root/include/TQtEmitter.h \
		../root/include/TVirtualX.interface.h \
		$(ROOTSYS)/include/TH1F.h \
		$(ROOTSYS)/include/TH1.h \
		../root/include/TAxis.h \
		../root/include/TAttAxis.h \
		../root/include/TArrayD.h \
		../root/include/TArray.h \
		../root/include/TArrayC.h \
		../root/include/TArrayS.h \
		../root/include/TArrayI.h \
		../root/include/TArrayF.h \
		../root/include/Foption.h \
		../root/include/TVectorFfwd.h \
		../root/include/TVectorDfwd.h \
		../root/include/TFitResultPtr.h \
		$(ROOTSYS)/include/TFrame.h \
		../root/include/TWbox.h \
		../root/include/TBox.h \
		../root/include/TColor.h \
		$(ROOTSYS)/include/TGedFrame.h \
		../root/include/TGFrame.h \
		../root/include/TGWindow.h \
		../root/include/TGObject.h \
		../root/include/TGClient.h \
		../root/include/TGDimension.h \
		../root/include/TGGC.h \
		../root/include/TRefCnt.h \
		../root/include/TGFont.h \
		../root/include/TGLayout.h \
		../root/include/TGString.h \
		$(ROOTSYS)/include/TGedEditor.h \
		../root/include/TVirtualPadEditor.h \
		../root/include/TMap.h \
		../root/include/THashTable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

V462_GateGenerator.o: src/V462_GateGenerator.cpp src/V462_GateGenerator.h \
		/usr/include/CAENVMElib.h \
		/usr/include/stdio.h \
		/usr/include/features.h \
		/usr/include/bits/predefs.h \
		/usr/include/sys/cdefs.h \
		/usr/include/bits/wordsize.h \
		/usr/include/gnu/stubs.h \
		/usr/include/gnu/stubs-32.h \
		/usr/include/bits/types.h \
		/usr/include/bits/typesizes.h \
		/usr/include/libio.h \
		/usr/include/_G_config.h \
		/usr/include/wchar.h \
		/usr/include/bits/wchar.h \
		/usr/include/wctype.h \
		/usr/include/endian.h \
		/usr/include/bits/endian.h \
		/usr/include/bits/byteswap.h \
		/usr/include/xlocale.h \
		/usr/include/bits/wchar2.h \
		/usr/include/bits/wchar-ldbl.h \
		/usr/include/gconv.h \
		/usr/include/bits/stdio-lock.h \
		/usr/include/bits/libc-lock.h \
		/usr/include/pthread.h \
		/usr/include/sched.h \
		/usr/include/time.h \
		/usr/include/bits/time.h \
		/usr/include/bits/sched.h \
		/usr/include/bits/pthreadtypes.h \
		/usr/include/bits/setjmp.h \
		/usr/include/errno.h \
		/usr/include/bits/errno.h \
		/usr/include/linux/errno.h \
		/usr/include/gnu/option-groups.h \
		/usr/include/bits/libio-ldbl.h \
		/usr/include/bits/stdio_lim.h \
		/usr/include/bits/sys_errlist.h \
		/usr/include/getopt.h \
		/usr/include/ctype.h \
		/usr/include/bits/stdio.h \
		/usr/include/bits/stdio2.h \
		/usr/include/bits/stdio-ldbl.h \
		/usr/include/stdint.h \
		/usr/include/stdlib.h \
		/usr/include/bits/waitflags.h \
		/usr/include/bits/waitstatus.h \
		/usr/include/sys/types.h \
		/usr/include/sys/select.h \
		/usr/include/bits/select.h \
		/usr/include/bits/sigset.h \
		/usr/include/sys/sysmacros.h \
		/usr/include/alloca.h \
		/usr/include/bits/stdlib.h \
		/usr/include/bits/stdlib-ldbl.h \
		/usr/include/malloc.h \
		/usr/include/CAENVMEoslib.h \
		/usr/include/CAENVMEtypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o V462_GateGenerator.o src/V462_GateGenerator.cpp

V550_CRAMS.o: src/V550_CRAMS.cpp src/V550_CRAMS.h \
		/usr/include/CAENVMElib.h \
		/usr/include/stdio.h \
		/usr/include/features.h \
		/usr/include/bits/predefs.h \
		/usr/include/sys/cdefs.h \
		/usr/include/bits/wordsize.h \
		/usr/include/gnu/stubs.h \
		/usr/include/gnu/stubs-32.h \
		/usr/include/bits/types.h \
		/usr/include/bits/typesizes.h \
		/usr/include/libio.h \
		/usr/include/_G_config.h \
		/usr/include/wchar.h \
		/usr/include/bits/wchar.h \
		/usr/include/wctype.h \
		/usr/include/endian.h \
		/usr/include/bits/endian.h \
		/usr/include/bits/byteswap.h \
		/usr/include/xlocale.h \
		/usr/include/bits/wchar2.h \
		/usr/include/bits/wchar-ldbl.h \
		/usr/include/gconv.h \
		/usr/include/bits/stdio-lock.h \
		/usr/include/bits/libc-lock.h \
		/usr/include/pthread.h \
		/usr/include/sched.h \
		/usr/include/time.h \
		/usr/include/bits/time.h \
		/usr/include/bits/sched.h \
		/usr/include/bits/pthreadtypes.h \
		/usr/include/bits/setjmp.h \
		/usr/include/errno.h \
		/usr/include/bits/errno.h \
		/usr/include/linux/errno.h \
		/usr/include/gnu/option-groups.h \
		/usr/include/bits/libio-ldbl.h \
		/usr/include/bits/stdio_lim.h \
		/usr/include/bits/sys_errlist.h \
		/usr/include/getopt.h \
		/usr/include/ctype.h \
		/usr/include/bits/stdio.h \
		/usr/include/bits/stdio2.h \
		/usr/include/bits/stdio-ldbl.h \
		/usr/include/stdint.h \
		/usr/include/stdlib.h \
		/usr/include/bits/waitflags.h \
		/usr/include/bits/waitstatus.h \
		/usr/include/sys/types.h \
		/usr/include/sys/select.h \
		/usr/include/bits/select.h \
		/usr/include/bits/sigset.h \
		/usr/include/sys/sysmacros.h \
		/usr/include/alloca.h \
		/usr/include/bits/stdlib.h \
		/usr/include/bits/stdlib-ldbl.h \
		/usr/include/malloc.h \
		/usr/include/CAENVMEoslib.h \
		/usr/include/CAENVMEtypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o V550_CRAMS.o src/V550_CRAMS.cpp

V551_Sequencer.o: src/V551_Sequencer.cpp src/V551_Sequencer.h \
		/usr/include/CAENVMElib.h \
		/usr/include/stdio.h \
		/usr/include/features.h \
		/usr/include/bits/predefs.h \
		/usr/include/sys/cdefs.h \
		/usr/include/bits/wordsize.h \
		/usr/include/gnu/stubs.h \
		/usr/include/gnu/stubs-32.h \
		/usr/include/bits/types.h \
		/usr/include/bits/typesizes.h \
		/usr/include/libio.h \
		/usr/include/_G_config.h \
		/usr/include/wchar.h \
		/usr/include/bits/wchar.h \
		/usr/include/wctype.h \
		/usr/include/endian.h \
		/usr/include/bits/endian.h \
		/usr/include/bits/byteswap.h \
		/usr/include/xlocale.h \
		/usr/include/bits/wchar2.h \
		/usr/include/bits/wchar-ldbl.h \
		/usr/include/gconv.h \
		/usr/include/bits/stdio-lock.h \
		/usr/include/bits/libc-lock.h \
		/usr/include/pthread.h \
		/usr/include/sched.h \
		/usr/include/time.h \
		/usr/include/bits/time.h \
		/usr/include/bits/sched.h \
		/usr/include/bits/pthreadtypes.h \
		/usr/include/bits/setjmp.h \
		/usr/include/errno.h \
		/usr/include/bits/errno.h \
		/usr/include/linux/errno.h \
		/usr/include/gnu/option-groups.h \
		/usr/include/bits/libio-ldbl.h \
		/usr/include/bits/stdio_lim.h \
		/usr/include/bits/sys_errlist.h \
		/usr/include/getopt.h \
		/usr/include/ctype.h \
		/usr/include/bits/stdio.h \
		/usr/include/bits/stdio2.h \
		/usr/include/bits/stdio-ldbl.h \
		/usr/include/stdint.h \
		/usr/include/stdlib.h \
		/usr/include/bits/waitflags.h \
		/usr/include/bits/waitstatus.h \
		/usr/include/sys/types.h \
		/usr/include/sys/select.h \
		/usr/include/bits/select.h \
		/usr/include/bits/sigset.h \
		/usr/include/sys/sysmacros.h \
		/usr/include/alloca.h \
		/usr/include/bits/stdlib.h \
		/usr/include/bits/stdlib-ldbl.h \
		/usr/include/malloc.h \
		/usr/include/CAENVMEoslib.h \
		/usr/include/CAENVMEtypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o V551_Sequencer.o src/V551_Sequencer.cpp

moc_Interface.o: moc_Interface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Interface.o moc_Interface.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

